### ISSUE TITLE
Only search suggestions for classes & properties

### ISSUE THREAD

**Issue by dipapaspyros** [LinDA-tools/transformation#22]
In [this call](https://github.com/LinDA-tools/transformation/blob/master/templates/transformation/csv_predicate.html#L189) the `class_property` parameter should be used instead of the more generic `q`, in order to avoid the suggestion of vocabularies.

**Comment by dipapaspyros** [comment]
I just noticed the `class_property` parameter is undocumented, sorry for this. The parameter was added recently to allow searching only for classes & properties without the need of two different API calls. Feel free to use it & I'll make sure to add it to the documentation.

**Comment by bbrand84** [comment]
I just replaced it. Is there anything more to consider here?

**Comment by lfarid** [comment]
The Transformation tool makes  calls to the vocabulary service  at 2 steps:
1) Predicate selection:to recieve suggestions for predicates, i.e. properties.
2) Semantic enrichment: to recieve suggestions for classes in order to describe the dataset.

IMHO, 1)  should use the parameter `property` and 2) the parameter `classes` . `class_property` would give back unsuitable results for the user and shouldn't be mixed up here.

@dipapaspyros please comment.

**Comment by dipapaspyros** [comment]
I think the most natural would be to only search `property` in case (1), and for `class` in case (2).

**Comment by bbrand84** [comment]
We also use the Service in the objects step \ reconciliation \ 5 star 

----- Ursprüngliche Nachricht -----
Von: "Dimitris Papaspyros" <notifications@github.com>
Gesendet: ‎15.‎07.‎2015 10:39
An: "LinDA-tools/transformation" <transformation@noreply.github.com>
Cc: "Benjamin Brand" <benjaminbrand@gmx.de>
Betreff: Re: [transformation] Only search suggestions for classes & properties(#22)

I think the most natural would be to only search property in case (1), and for class in case (2).
